[versions]
#Project Settings
compileSdk = "36"
targetSdk = "36"
minSdk = "26"
versionCode = "1"
versionName = "1.0.0"

#Android & Kotlin
agp = "9.1.1"
kotlin = "2.3.21"
coreKtx = "1.18.0"

#Lifecycle
lifecycleRuntimeKtx = "2.10.0"

#Compose
activityCompose = "1.13.0"
composeBom = "2026.04.01"

#Coil
coil = "3.4.0"

#Hilt
daggerHilt = "2.59.2"
daggerHiltNavigationCompose = "1.3.0"

#Kotlin Coroutines
kotlinxCoroutines = "1.11.0"

#Kotlin Serialization
kotlinxSerialization = "1.11.0"

# kotlin datetime
kotlinxDatetime = "0.8.0"

#Ksp
ksp = "2.3.6"

#Network
retrofit = "3.0.0"
okhttp = "5.3.2"

#Navigation
navigation = "1.2.0-alpha02" # Result Return 을 위한 ResultEventBusNavEntryDecorator 가 1.2.0-alpha02 부터 지원하여, stable 이 아님에도 선택하였습니다

#CameraX
cameraX = "1.6.1"

#DataStore
datastore = "1.1.7"

#ktlint
ktlint = "14.2.0"

#Kakao Login
kakao-user = "2.23.2"

#ML Kit
mlkitSubjectSegmentation = "16.0.0-beta1"

#java
javaxInject = "1"

[libraries]
#gradle plugin
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

# Kotlin
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

#Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-navigation-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleRuntimeKtx" }

#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Retrofit
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

#Hilt
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "daggerHiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", name = "hilt-compiler", version.ref = "daggerHilt" }
hilt-viewmodel = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "daggerHiltNavigationCompose" }

#Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }

#Navigation
navigation-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation" }
kakao-sdk-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakao-user" }

#CameraX
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }

#DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#Java
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }

#ML Kit
google-mlkit-subject-segmentation = { group = "com.google.android.gms", name = "play-services-mlkit-subject-segmentation", version.ref = "mlkitSubjectSegmentation" }

[bundles]
hilt = [
    "hilt-navigation",
    "hilt-android",
]

network = [
    "okhttp",
    "okhttp-logging-interceptor",
    "retrofit",
    "retrofit-kotlin-serialization-converter",
]

navigation = [
    "androidx-lifecycle-navigation-viewmodel",
    "navigation-runtime",
    "navigation-ui",
]

camerax = [
    "camerax-core",
    "camerax-camera2",
    "camerax-lifecycle",
    "camerax-view",
]

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

#Custom Plugin
parfait-android-application = { id = "com.teamyg.parfait.plugin.android.application" }
parfait-android-application-signing = { id = "com.teamyg.parfait.plugin.android.application.signing" }
parfait-android-library = { id = "com.teamyg.parfait.plugin.android.library" }
parfait-dagger-hilt-core = { id = "com.teamyg.parfait.plugin.dagger.hilt.core" }
parfait-dagger-hilt-compose = { id = "com.teamyg.parfait.plugin.dagger.hilt.compose" }
parfait-jetpack-compose = { id = "com.teamyg.parfait.plugin.jetpack.compose" }
parfait-kotlin-jvm = { id = "com.teamyg.parfait.plugin.kotlin.jvm" }
parfait-module-data = { id = "com.teamyg.parfait.plugin.module.data" }
parfait-module-domain = { id = "com.teamyg.parfait.plugin.module.domain" }
parfait-module-feature-impl = { id = "com.teamyg.parfait.plugin.module.feature.impl" }
parfait-module-feature-api = { id = "com.teamyg.parfait.plugin.module.feature.api" }
