name: 기타
description: 기존의 라벨로는 표시할 수 없는 내역을 작성합니다.
title: "[Etc]: "
labels: ["기타"]
body:
  - type: markdown
    attributes:
      value: |
        기존 라벨에 해당하지 않는 이슈를 작성해주세요.
  - type: checkboxes
    id: label-check
    attributes:
      label: 다른 라벨에 해당하지 않나요?
      description: 기능, 버그, 리팩토링, 문서화, 배포, 빌드 등 다른 라벨에 해당하지 않는지 확인해주세요.
      options:
        - label: 기존 라벨로는 분류할 수 없는 이슈임을 확인했습니다.
          required: true
  - type: textarea
    id: content
    attributes:
      label: 이슈 내용
      description: 어떤 내용인지 구체적으로 설명해주세요.
      placeholder: 이슈에 대해서 설명해주세요!
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 참고 사항
      description: 관련 링크, 자료 등.
    validations:
      required: false